version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing make
          command: apt install -y build-essential

      - run:
          name: Build
          command: make